# Etapa 1: Construcción de React
FROM node:24 as builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: NGINX sirve archivos estáticos
FROM nginx:alpine

# Copiar archivos construidos al directorio de NGINX
COPY --from=builder /app/build /usr/share/nginx/html

# (Opcional) Config personalizada de nginx
# COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto estándar de NGINX
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
